POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtla2F5dHRpcyIsImlkIjoiNWY5MDA2NjRiNjgzMGIwN2Q4NzI2MDE5IiwiaWF0IjoxNjAzMjc0OTY3fQ.-UGtgnHDPxpZ8MrkmVFDKCLdNFMSlClehp6j_DM5BeM


{
    "title": "Pastablogi",
  "author": "Lord Pasta",
  "url": "www.hienostopasta.fi",
  "likes": 33,
  "userId": "5f900664b6830b07d8726019"
}